stages:
  - deploy

deploy:
  stage: deploy
  image: node:18
  before_script:
    - echo "📦 Installing Railway CLI..."
    - npm install -g @railway/cli

  script:
    - echo "🚀 Deploying..."
    - railway up --service=subscription_bot --detach
