variables:
  # These should be defined in Settings → CI/CD → Variables
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  SVC_ID: subscription_bot

stages:
  - deploy

deploy:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  script:
    - echo "Deploying service $SVC_ID"
    - railway up --service=$SVC_ID