stages:
  - deploy

deploy:
  stage: deploy
  image: node:18
  before_script:
    - npm install -g @railway/cli
  script:
    - railway up --project $RAILWAY_PROJECT_ID --token $RAILWAY_TOKEN --service=subscription_bot --detach
