stages:
  - deploy

deploy:
  stage: deploy
  image: node:18
  before_script:
    - npm install -g railway
    - mkdir -p ~/.railway
    - echo "$RAILWAY_CONFIG" | base64 -d > ~/.railway/config.json
  script:
    - railway up --service=subscription_bot --detach
