variables:
  # These should be defined in Settings → CI/CD → Variables
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  SVC_ID: subscription_bot

stages:
  - deploy

deploy:
  stage: deploy
  image: node:18
  before_script:
    - echo "📦 Installing Railway CLI..."
    - npm install -g @railway/cli

    - echo "Token starts with: ${RAILWAY_TOKEN:0:10}..."
    - echo "Project ID: $RAILWAY_PROJECT_ID"
  script:
    - echo "Deploying service $SVC_ID"
    - railway up --service=$SVC_ID