deploy-job:
  image: ghcr.io/railwayapp/cli:latest
  variables:
    RAILWAY_TOKEN: $RAILWAY_TOKEN
    SVC_ID: my-service
  script:
    - railway login --token "$RAILWAY_TOKEN"
    - railway up --service=$SVC_ID